"""Protocol definitions (§6, §14, §17)."""
from __future__ import annotations
from typing import IO, Iterable, Literal, Protocol, Sequence, runtime_checkable
from urisolver.destinations import Destination
from urisolver.info import ResourceInfo
from urisolver.results import MaterializedResult
from urisolver.selection import Selection

@runtime_checkable
class StreamFacet(Protocol):
    def open(self, mode: Literal["rb"] = "rb") -> IO[bytes]: ...
    def readable_ranges(self) -> bool: ...

@runtime_checkable
class ArrayFacet(Protocol):
    shape: tuple[int, ...]
    dtype: str
    chunks: tuple[tuple[int, ...], ...] | None
    def __getitem__(self, selection: object) -> object: ...

@runtime_checkable
class TableFacet(Protocol):
    columns: tuple[str, ...]
    num_rows: int | None
    def read(self, columns: Sequence[str] | None = None) -> object: ...

@runtime_checkable
class ContainerFacet(Protocol):
    def keys(self) -> Iterable[str]: ...
    def __getitem__(self, key: str) -> ResolvedResource: ...
    def __len__(self) -> int: ...

@runtime_checkable
class ResolvedResource(Protocol):
    @property
    def uri(self) -> str: ...
    @property
    def resolved_uri(self) -> str: ...
    @property
    def protocol(self) -> str: ...
    def info(self) -> ResourceInfo: ...
    def materialize(self, destination: Destination, *, selection: Selection | None = None, **kwargs: object) -> MaterializedResult: ...
    def facets(self) -> frozenset[str]: ...
    def facet(self, name: str) -> object: ...
    def supports(self, name: str) -> bool: ...
    def capabilities(self) -> frozenset[str]: ...
    @property
    def native(self) -> object: ...

@runtime_checkable
class Resolver(Protocol):
    api_version: int
    opaque_payload: bool
    def resolve(self, uri: str, context: object) -> ResolvedResource: ...
    def close(self) -> None: ...
